
######################################
### Loss manager parameters
use_ref_disc: ${use_ref_disc} # enable the usage of the reference discriminator

######################################
### Generator losses parameters
generator_losses:
  reduction: sum # mean, sum

  l1:
    weight: 0

  # same as l1 but with a smooth mask applied to change weight
  # near and over the objects
  l1_smooth_masked:
    weight: 5 # overall weight of the loss
    kwargs:
      channels: ${data.object_datasets.n} # number of channels of the mask, equal to the number of classes
      obj_weight: 0.1 # weight of the loss in the object area
      bg_weight: 1.0 # weight of the loss in the background area
      kernel_size: 31 # size of the linear kernel used to smooth the mask

  adversarial:
    weight: 20

  ref_adversarial:
    weight: 8

  resnet_pl:
    weight: 0
    kwargs:
      weights_path: ${location.loss_models}

  # same as resnet_pl but with a smooth mask applied to change weight 
  # near and over the objects
  resnet_pl_smooth_masked:
    weight: 0.3
    kwargs:
      channels: ${data.object_datasets.n} # number of channels of the mask, equal to the number of classes
      weights_path: ${location.loss_models}
      obj_weight: 0.1 # weight of the loss in the object area
      bg_weight: 1.0 # weight of the loss in the background area
      kernel_size: 31 # size of the linear kernel used to smooth the mask

# genrator regularitions
generator_reg:
  g_reg_every: 4 # n steps between 2 generator updarte regularizations
  path_lenght:
    weight: 5
    decay: 0.01

######################################
### Discriminator losses parameters
discriminator_losses:
  logistic:
    weight: 5

# discriminator regularitions
discriminator_reg: # TODO sistema i parametri
  d_reg_every: 16 # n steps between 2 discriminator updarte regularizations
  r1:
    weight: 3

######################################
### Discriminator losses parameters
ref_discriminator_losses:
  logistic:
    weight: 5

# discriminator regularitions
ref_discriminator_reg: # TODO sistema i parametri
  d_reg_every: 16 # n steps between 2 discriminator updarte regularizations
  r1:
    weight: 3